### ISSUE TITLE
Import PVT_K1

### ISSUE THREAD

**Issue by metallicusdev** [learnforpractice/pyeoskit#10]
Is there any way inside pyeoskit to import PVT_K1 or change 5... keys to PVT_K1?

**Comment by learnforpractice** [comment]
I'm not sure whether I understand. Private keys are typically encoded using the Base58 format. Where the `PVT_K1` comes from?

**Comment by metallicusdev** [comment]
That is the format used in eosjs, plus supported in other eosio tools

https://github.com/EOSIO/eosjs-ecc/issues/12

EOS... pub keys, etc are considered "legacy"

**Comment by learnforpractice** [comment]
Yeah, the representation of public keys are different, but private keys are the same?

**Comment by metallicusdev** [comment]
Yes if you look in eosjs, uses PVT_K1, PVT_R1, etc

**Comment by learnforpractice** [comment]
Fixed by 705d5e0d3fbe9261fcc22812b0badeca5ef225d6
