### ISSUE TITLE
how to set the connection to mainnet?

### ISSUE THREAD

**Issue by softbug123** [learnforpractice/pyeoskit#3]
when i run the push command,the python tell me:

WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F4D9F9198>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /v1/chain/get_info

so,i found it connect the 127.0.0.1:8888,

how can i set the connectin info?

**Comment by learnforpractice** [comment]
from pyeoskit import eosapi
eosapi.set_nodes(['http://127.0.0.1:8888'])

Change ['http://127.0.0.1:8888'] to ip addresses what ever you want.

There are some examples in:

https://github.com/learnforpractice/pyeoskit/blob/master/Docs/eosapi.ipynb <https://github.com/learnforpractice/pyeoskit/blob/master/Docs/eosapi.ipynb>

**Comment by softbug123** [comment]
thanks!
btw, in the pycharm,i can not see the auto hint for pyeoskit's class.
do we have a sdk api refenerce list? 
i can not see the eosapi.set_nodes funciton if i dont ask u.

**Comment by learnforpractice** [comment]
This is an ongoing project. Any help will be appreciated.

Feel free to submit a pull request if you can.
