### ISSUE TITLE
http proxy issue

### ISSUE THREAD

**Issue by encoderlee** [learnforpractice/pyeoskit#8]
The following code should work.
```
import os
os.environ['HTTP_PROXY'] =  'http://prox:1234'
os.environ['HTTPS_PROXY'] = 'https://proxy:5678'
```

Another method:

```
from pyeoskit import eosapi

proxies = {
     'http': 'http://proxy1.com',
     'https': 'https://proxy2.com',
}
eosapi.session.proxies = proxies
```

_Originally posted by @learnforpractice in https://github.com/learnforpractice/pyeoskit/issues/7#issuecomment-1066131854_

**Comment by encoderlee** [comment]
this code work ok ,but
[chainnative.py](https://github.com/learnforpractice/pyeoskit/blob/d4764799093f666db6c43dd66238ddb62290acad/pysrc/chainnative.py)

ChainNative.get_abi_sync() use httpx.post
it's post without proxy

**Comment by encoderlee** [comment]
why both use 'requests' and 'httpx'?
could you just use 'requests' only?

**Comment by learnforpractice** [comment]
See the latest commit: 8f255a95040a51644ac2fb438bcbaaf06187fb7f

**Comment by encoderlee** [comment]
nice
